// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteHistoryByIdData, DeleteHistoryByIdErrors, DeleteHistoryByIdResponses, DeleteHistoryPurgeData, DeleteHistoryPurgeResponses, GetHistoryByIdData, GetHistoryByIdErrors, GetHistoryByIdResponses, GetHistoryData, GetHistoryResponses, GetHistoryWordsData, GetHistoryWordsResponses, GetSearchByWordData, GetSearchByWordErrors, GetSearchByWordResponses, PostHistoryData, PostHistoryResponses, PutHistoryByIdData, PutHistoryByIdErrors, PutHistoryByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List paginated search history records.
 */
export const getHistory = <ThrowOnError extends boolean = false>(options?: Options<GetHistoryData, ThrowOnError>): RequestResult<GetHistoryResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHistoryResponses, unknown, ThrowOnError>({ url: '/history', ...options });

/**
 * Create a search history record.
 */
export const postHistory = <ThrowOnError extends boolean = false>(options?: Options<PostHistoryData, ThrowOnError>): RequestResult<PostHistoryResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostHistoryResponses, unknown, ThrowOnError>({ url: '/history', ...options });

/**
 * List unique searched words with their history counts.
 */
export const getHistoryWords = <ThrowOnError extends boolean = false>(options?: Options<GetHistoryWordsData, ThrowOnError>): RequestResult<GetHistoryWordsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHistoryWordsResponses, unknown, ThrowOnError>({ url: '/history/words', ...options });

/**
 * Delete all search history records.
 */
export const deleteHistoryPurge = <ThrowOnError extends boolean = false>(options?: Options<DeleteHistoryPurgeData, ThrowOnError>): RequestResult<DeleteHistoryPurgeResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<DeleteHistoryPurgeResponses, unknown, ThrowOnError>({ url: '/history/purge', ...options });

/**
 * Delete a search history record.
 */
export const deleteHistoryById = <ThrowOnError extends boolean = false>(options: Options<DeleteHistoryByIdData, ThrowOnError>): RequestResult<DeleteHistoryByIdResponses, DeleteHistoryByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteHistoryByIdResponses, DeleteHistoryByIdErrors, ThrowOnError>({ url: '/history/{id}', ...options });

/**
 * Get one search history record by ID.
 */
export const getHistoryById = <ThrowOnError extends boolean = false>(options: Options<GetHistoryByIdData, ThrowOnError>): RequestResult<GetHistoryByIdResponses, GetHistoryByIdErrors, ThrowOnError> => (options.client ?? client).get<GetHistoryByIdResponses, GetHistoryByIdErrors, ThrowOnError>({ url: '/history/{id}', ...options });

/**
 * Update a search history record.
 */
export const putHistoryById = <ThrowOnError extends boolean = false>(options: Options<PutHistoryByIdData, ThrowOnError>): RequestResult<PutHistoryByIdResponses, PutHistoryByIdErrors, ThrowOnError> => (options.client ?? client).put<PutHistoryByIdResponses, PutHistoryByIdErrors, ThrowOnError>({
    url: '/history/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Find the correct Dutch article for a word.
 */
export const getSearchByWord = <ThrowOnError extends boolean = false>(options: Options<GetSearchByWordData, ThrowOnError>): RequestResult<GetSearchByWordResponses, GetSearchByWordErrors, ThrowOnError> => (options.client ?? client).get<GetSearchByWordResponses, GetSearchByWordErrors, ThrowOnError>({ url: '/search/{word}', ...options });
