// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8806' | (string & {});
};

export type GetHistoryData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/history';
};

export type GetHistoryResponses = {
    /**
     * A paginated list of search history records.
     */
    200: {
        data: Array<{
            id: number;
            word: string;
            result: string | null;
            createdAt: string;
        }>;
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    };
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type PostHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/history';
};

export type PostHistoryResponses = {
    /**
     * The created history record.
     */
    201: {
        id: number;
        word: string;
        result: string | null;
        createdAt: string;
    };
};

export type PostHistoryResponse = PostHistoryResponses[keyof PostHistoryResponses];

export type GetHistoryWordsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/history/words';
};

export type GetHistoryWordsResponses = {
    /**
     * A paginated list of unique words and counts.
     */
    200: {
        data: Array<{
            word: string;
            count: number;
        }>;
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    };
};

export type GetHistoryWordsResponse = GetHistoryWordsResponses[keyof GetHistoryWordsResponses];

export type DeleteHistoryPurgeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/history/purge';
};

export type DeleteHistoryPurgeResponses = {
    /**
     * All history records were deleted.
     */
    204: void;
};

export type DeleteHistoryPurgeResponse = DeleteHistoryPurgeResponses[keyof DeleteHistoryPurgeResponses];

export type DeleteHistoryByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/history/{id}';
};

export type DeleteHistoryByIdErrors = {
    /**
     * History record not found.
     */
    404: unknown;
};

export type DeleteHistoryByIdResponses = {
    /**
     * History record deleted.
     */
    204: void;
};

export type DeleteHistoryByIdResponse = DeleteHistoryByIdResponses[keyof DeleteHistoryByIdResponses];

export type GetHistoryByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/history/{id}';
};

export type GetHistoryByIdErrors = {
    /**
     * History record not found.
     */
    404: unknown;
};

export type GetHistoryByIdResponses = {
    /**
     * The requested history record.
     */
    200: {
        id: number;
        word: string;
        result: string | null;
        createdAt: string;
    };
};

export type GetHistoryByIdResponse = GetHistoryByIdResponses[keyof GetHistoryByIdResponses];

export type PutHistoryByIdData = {
    body: {
        word?: string;
        result?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/history/{id}';
};

export type PutHistoryByIdErrors = {
    /**
     * History record not found.
     */
    404: unknown;
};

export type PutHistoryByIdResponses = {
    /**
     * The updated history record.
     */
    200: {
        id: number;
        word: string;
        result: string | null;
        createdAt: string;
    };
};

export type PutHistoryByIdResponse = PutHistoryByIdResponses[keyof PutHistoryByIdResponses];

export type GetSearchByWordData = {
    body?: never;
    path: {
        word: string;
    };
    query?: never;
    url: '/search/{word}';
};

export type GetSearchByWordErrors = {
    /**
     * The search failed.
     */
    500: {
        error: string;
    };
};

export type GetSearchByWordError = GetSearchByWordErrors[keyof GetSearchByWordErrors];

export type GetSearchByWordResponses = {
    /**
     * The article result for the word.
     */
    200: string;
};

export type GetSearchByWordResponse = GetSearchByWordResponses[keyof GetSearchByWordResponses];
